name: Tag releases to main

on:
  push:
    branches:
      - main

jobs:
  semver-tag:
    name: Apply semantic version tags
    uses: Quiqui-dev//.github/workflows/tf-module-release-workflow.yml@2
    permissions:
      contents: write
    secrets: inherit
